version: '3'
services:
  umami:
    image: 'ghcr.io/umami-software/umami:postgresql-latest'
    container_name: 'umami'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/umami
      - DATABASE_TYPE=postgresql
      - HASH_SALT=${UMAMI_HASH}
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    container_name: 'umami-db'
    environment:
      - POSTGRES_DB=umami
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  umami-db-data:

networks:
  default:
    name: okr-network
    external: true
